App = {
    "options": {
        "version": "1.7.0",
        "versions": {},
        "assets": {},
        "ids": {},
        "prefix": {},
        "year": "2020",
        "layers": [],
        "classification": null,
        "integration": null,
        "mosaics": null,
        "biomes": null,
        "collection31": null,
        "collection41": null,
        "collection50": null,
        "collection60": null,
        "collection60f": null,
        "states": null,
        "incidentes": null,
        "difference": null,
        "vis": {},
        "prevalenceList": [],
        "legend": {},
    },
    "init": function() {},
    "setVersion": function() {},
    "getPrevalenceList": function() {},
    "getClassifications": function() {},
    "getMosaics": function() {},
    "getRegions": function() {},
    "getCollections": function() {},
    "calculateStates": function() {},
    "calculateIncidents": function() {},
    "calculateFilterDiff": function() {},
    "loadLayers": function() {},
    "loadData": function() {},
    "ui": {},
  
}